kind: pipeline
name: quake3

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ich777/quake3
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
    